### ISSUE TITLE
Add "Run as admin" option

### ISSUE THREAD

**Issue by frmdstryr** [brunonova/nautilus-admin#2]
Would be nice to have a "Run as admin" menu item for files using either pkexec or gksu.

**Comment by brunonova** [comment]
I don't know.
Adding an option to easily allow to run any executable/script as root could be very dangerous.

This can already be done by opening the folder as admin, and then execute the file.

**Comment by brunonova** [comment]
I'm not going to implement this, at least for now.
This option could be very dangerous, I think.
If more people request it, I may implement it.

**Comment by Baltix** [comment]
Please implement Run as Administrator on executable text files - now users simply can't install lots of important software on Ubuntu or Debian, for example drivers for Samsung printers: www.samsungsetup.com/TS/Files/RDS_XML/web_install_agent/linux/SamsungPrinterInstaller.tar.gz

User should run install-printer.sh (or install.sh) using root privileges, without root privileges this script terminates with error:
***\* Root privileges are required

*install.sh scripts aren't executed if I open the folder as admin, and then double click on the file or choose "Open" from context menu - then these executable scripts are simply opened in Text editor (gedit)

**Comment by brunonova** [comment]
> *install.sh scripts aren't executed if I open the folder as admin, and then double click on the file or choose "Open" from context menu - then these executable scripts are simply opened in Text editor (gedit)

That's because Nautilus is configured by default to open executable scripts in the text editor, instead of executing them.

[Follow these instructions](http://askubuntu.com/questions/286621/how-do-i-run-executable-scripts-in-nautilus) to change that behavior in Nautilus, when running as admin. It should work.

**Comment by Baltix** [comment]
[25_nautilus-baltix.gschema.override](https://github.com/brunonova/nautilus-admin/files/321706/25_nautilus-baltix.gschema.override.txt)

Sorry, you are not right, I've already configured Nautilus to execute text scripts - I've put attached nautilus-baltix.gschema.override file to /usr/share/glib-2.0/schemas/ and executed
sudo update-gconf-defaults 
Nautilus in my system asks for executing text scripts if I click on executable text file, but only when it is running as a user - scripts aren't executed if I open the folder as admin (root) :(
That's why I'm asking to implement Run as Administrator on executable text files

Thanks for creating useful plugin,
Mantas Kriaučiūnas

**Comment by brunonova** [comment]
That's strange. It works for me in Ubuntu 16.04, and I configured that using the settings dialog. Try that.
You could also try to run this command:

```
sudo -H gsettings set org.gnome.nautilus.preferences executable-text-activation ask
```

But maybe I'll implement this feature when I have time.

**Comment by brunonova** [comment]
This feature will be in the next version.
Thanks again to @frmdstryr!
