### ISSUE TITLE
Dirs do not seem to work completely with 18.04

### ISSUE THREAD

**Issue by ddnexus** [brunonova/nautilus-admin#42]
While the "Edit as Admin" works with files, the "Open as Admin" seems to miss the context menu for deleting files. It opens the dir window, the files in it look locked (although if you try to open them you are asked for the admin password). You can edit and save the files. You can move them to the trash bin icon and you are asked to delete them imediately, which works.

The previous behavior was better though. With "Open as Admin" you were actually root, so no further password required, and the trash-bin was the root trash-bin, plus the Delete context menu and keyboard shortcut were actually working as expected.

Tried with the latest release.

**Comment by brunonova** [comment]
This is due to #29.

It's not possible to run graphical applications as root under Wayland. It's also dangerous to run graphical applications as root.
So, the extension was updated to use gvfs' new admin backend, which doesn't require running Nautilus or Gedit as root.
There are some things that don't work there, as you've seen. That's a bug in the admin backend.

You're still free to use the last version ([0.2.5][1]) that actually opens Nautilus/Gedit as root, unless you're using Wayland.

[1]: https://github.com/brunonova/nautilus-admin/releases/tag/v0.2.5

**Comment by ddnexus** [comment]
Wayland, till 2020... no, thank you! :). Thanks for the info and the nice
software!
